@SummaryList
Feature: Holiday Entitlement Calculator Summary List
  As an employee
  I want to be able to see my summary list at the end of the questionnaire
  So that I can review my answers


  Scenario Outline: Summary List
    Given I navigate to the endpoint "/calculate-your-holiday-entitlement/<Endpoint>"
    Then I should be on the holiday entitlement summary
    And the summary list answers contain:
      | Question                                                       | Answer                       |
      | Does the employee work irregular hours or for part of the year | <Irregular Hours>            |
      | Is the holiday entitlement based on                            | <Entitlement Basis>          |
      | When does the leave year start                                 | <Holiday Year>               |
      | How many hours has the employee worked in the pay period       | <Hours Worked In Pay Period> |
      | Do you want to work out holiday                                | <Entitlement Type>           |
      | Number of days worked per week                                 | <Days Worked a Week>         |
      | Number of hours worked per week                                | <Hours Worked a Week>        |
      | What was the employment start date                             | <Start Date>                 |
      | What was the employment end date                               | <End Date>                   |
      | How many hours in each shift                                   | <Hours per Shift>            |
      | How many shifts will be worked year shift pattern              | <Shifts per Pattern>         |
      | How many days in the shift pattern                             | <Days in Shift Pattern>      |

    Examples:
      | Endpoint                                                                             | Irregular Hours | Entitlement Basis     | Entitlement Type                                               | Start Date      | End Date     | Holiday Year   | Days Worked a Week | Hours Worked a Week | Hours Worked In Pay Period | Hours per Shift | Shifts per Pattern | Days in Shift Pattern |
      | /y/irregular-hours-and-part-year/2025-01-01/50.0                                     | Yes             | -                     | -                                                              | -               | -            | 1 January 2025 | -                  | -                   | 50.0                       | -               | -                  | -                     |
      | /y/regular/days-worked-per-week/full-year/5.0                                        | No              | days worked per week  | for a full leave year                                          | -               | -            | -              | 5.0                | -                   | -                          | -               | -                  | -                     |
      | /y/regular/days-worked-per-week/full-year/2.0                                        | No              | days worked per week  | for a full leave year                                          | -               | -            | -              | 2.0                | -                   | -                          | -               | -                  | -                     |
      | /y/regular/days-worked-per-week/starting/2024-02-02/2024-01-01/3.0                   | No              | days worked per week  | for someone starting part way through a leave year             | 2 February 2024 | -            | 1 January 2024 | 3.0                | -                   | -                          | -               | -                  | -                     |
      | /y/regular/days-worked-per-week/leaving/2024-03-03/2024-01-01/4.0                    | No              | days worked per week  | for someone leaving part way through a leave year              | -               | 3 March 2024 | 1 January 2024 | 4.0                | -                   | -                          | -               | -                  | -                     |
      | /y/regular/days-worked-per-week/starting-and-leaving/2024-02-02/2024-03-03/2.0       | No              | days worked per week  | for someone starting and leaving part way through a leave year | 2 February 2024 | 3 March 2024 | -              | 2.0                | -                   | -                          | -               | -                  | -                     |
      | /y/regular/hours-worked-per-week/full-year/40.0/5.0                                  | No              | hours worked per week | for a full leave year                                          | -               | -            | -              | 5.0                | 40.0                | -                          | -               | -                  | -                     |
      | /y/regular/hours-worked-per-week/full-year/25.0/3.0                                  | No              | hours worked per week | for a full leave year                                          | -               | -            | -              | 3.0                | 25.0                | -                          | -               | -                  | -                     |
      | /y/regular/hours-worked-per-week/starting/2024-02-02/2024-01-01/38.0/5.0             | No              | hours worked per week | for someone starting part way through a leave year             | 2 February 2024 | -            | 1 January 2024 | 5.0                | 38.0                | -                          | -               | -                  | -                     |
      | /y/regular/hours-worked-per-week/leaving/2024-03-03/2024-01-01/37.0/5.0              | No              | hours worked per week | for someone leaving part way through a leave year              | -               | 3 March 2024 | 1 January 2024 | 5.0                | 37.0                | -                          | -               | -                  | -                     |
      | /y/regular/hours-worked-per-week/starting-and-leaving/2024-02-02/2024-03-03/40.0/4.0 | No              | hours worked per week | for someone starting and leaving part way through a leave year | 2 February 2024 | 3 March 2024 | -              | 4.0                | 40.0                | -                          | -               | -                  | -                     |
      | /y/regular/compressed-hours/full-year/40.0/5.0                                       | No              | compressed hours      | for a full leave year                                          | -               | -            | -              | 5.0                | 40.0                | -                          | -               | -                  | -                     |
      | /y/regular/compressed-hours/full-year/25.0/3.0                                       | No              | compressed hours      | for a full leave year                                          | -               | -            | -              | 3.0                | 25.0                | -                          | -               | -                  | -                     |
      | /y/regular/compressed-hours/starting/2024-02-02/2024-01-01/38.0/5.0                  | No              | compressed hours      | for someone starting part way through a leave year             | 2 February 2024 | -            | 1 January 2024 | 5.0                | 38.0                | -                          | -               | -                  | -                     |
      | /y/regular/compressed-hours/leaving/2024-03-03/2024-01-01/37.0/5.0                   | No              | compressed hours      | for someone leaving part way through a leave year              | -               | 3 March 2024 | 1 January 2024 | 5.0                | 37.0                | -                          | -               | -                  | -                     |
      | /y/regular/compressed-hours/starting-and-leaving/2024-02-02/2024-03-03/40.0/4.0      | No              | compressed hours      | for someone starting and leaving part way through a leave year | 2 February 2024 | 3 March 2024 | -              | 4.0                | 40.0                | -                          | -               | -                  | -                     |
      | /y/regular/annualised-hours/full-year                                                | No              | annualised hours      | for a full leave year                                          | -               | -            | -              | -                  | -                   | -                          | -               | -                  | -                     |
      | /y/regular/annualised-hours/starting/2024-02-02/2024-01-01                           | No              | annualised hours      | for someone starting part way through a leave year             | 2 February 2024 | -            | 1 January 2024 | -                  | -                   | -                          | -               | -                  | -                     |
      | /y/regular/annualised-hours/leaving/2024-03-03/2024-01-01                            | No              | annualised hours      | for someone leaving part way through a leave year              | -               | 3 March 2024 | 1 January 2024 | -                  | -                   | -                          | -               | -                  | -                     |
      | /y/regular/annualised-hours/starting-and-leaving/2024-02-02/2024-03-03               | No              | annualised hours      | for someone starting and leaving part way through a leave year | 2 February 2024 | 3 March 2024 | -              | -                  | -                   | -                          | -               | -                  | -                     |
      | /y/regular/shift-worker/full-year/6.0/5/9.0                                          | No              | shifts                | -                                                              | -               | -            | -              | -                  | -                   | -                          | 6.0             | -                  | 9.0                   |
      | /y/regular/shift-worker/full-year/7.0/5/10.0                                         | No              | shifts                | -                                                              | -               | -            | -              | -                  | -                   | -                          | 7.0             | -                  | 10.0                  |
      | /y/regular/shift-worker/starting/2024-02-02/2024-01-01/5.0/5/5.0                     | No              | shifts                | -                                                              | 2 February 2024 | -            | 1 January 2024 | -                  | -                   | -                          | 5.0             | -                  | 5.0                   |
      | /y/regular/shift-worker/leaving/2024-03-03/2024-01-01/12.0/5/6.0                     | No              | shifts                | -                                                              | -               | 3 March 2024 | 1 January 2024 | -                  | -                   | -                          | 12.0            | -                  | 6.0                   |
      | /y/regular/shift-worker/starting-and-leaving/2024-02-02/2024-03-03/5.0/5/7.0         | No              | shifts                | -                                                              | 2 February 2024 | 3 March 2024 | -              | -                  | -                   | -                          | 5.0             | -                  | 7.0                   |